/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <vslutov@yandex.ru> wrote this file.   As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy me a beer in return.      Vladimir Lutov
 * ----------------------------------------------------------------------------
 */

#ifndef MAIN
#define MAIN

#include <opencv2/opencv.hpp>

namespace hockey {
    // Global variables
    cv::Mat frame; //current frame
    cv::Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
    int keyboard; //input from keyboard

    void
    help();

    cv::Ptr<cv::BackgroundSubtractor>
    prepare_model(const std::string &videoFilename);

    void
    process_video(const std::string &videoFilename);

    void
    applyMask(const cv::Mat &src, cv::Mat &dst, const cv::Mat &mask);

    ssize_t
    dfs(uchar *p, ssize_t rows, ssize_t cols, ssize_t x, ssize_t y, uchar in, uchar out);

    void
    label(const cv::Mat &src, cv::Mat &dst);

    void
    colorize(const cv::Mat &src, cv::Mat &dst);
}

#endif // MAIN

